// Country Data - 195 Countries

const COUNTRIES_DATA = {
  'US': {
    name: 'Hoa Kỳ',
    code: 'USA',
    flag: '🇺🇸',
    gdp: 27360,
    gdpGrowth: 2.5,
    inflation: 3.2,
    unemployment: 3.7,
    population: 339,
    gdpPerCapita: 80600,
    golds: 261.5,
    fdi: 380,
  },
  'CN': {
    name: 'Trung Quốc',
    code: 'CHN',
    flag: '🇨🇳',
    gdp: 17734,
    gdpGrowth: 5.2,
    inflation: 2.1,
    unemployment: 4.3,
    population: 1412,
    gdpPerCapita: 12500,
    golds: 2261.0,
    fdi: 163,
  },
  'DE': {
    name: 'Đức',
    code: 'DEU',
    flag: '🇩🇪',
    gdp: 4080,
    gdpGrowth: -0.3,
    inflation: 2.4,
    unemployment: 2.6,
    population: 84,
    gdpPerCapita: 48500,
    golds: 3710.0,
    fdi: 56,
  },
  'JP': {
    name: 'Nhật Bản',
    code: 'JPN',
    flag: '🇯🇵',
    gdp: 4231,
    gdpGrowth: 1.9,
    inflation: 2.0,
    unemployment: 2.4,
    population: 124,
    gdpPerCapita: 34100,
    golds: 765.2,
    fdi: 62,
  },
  'IN': {
    name: 'Ấn Độ',
    code: 'IND',
    flag: '🇮🇳',
    gdp: 3736,
    gdpGrowth: 7.2,
    inflation: 4.8,
    unemployment: 3.2,
    population: 1417,
    gdpPerCapita: 2640,
    golds: 848.0,
    fdi: 85,
  },
  'GB': {
    name: 'Vương Quốc Anh',
    code: 'GBR',
    flag: '🇬🇧',
    gdp: 3332,
    gdpGrowth: 0.5,
    inflation: 3.9,
    unemployment: 4.0,
    population: 68,
    gdpPerCapita: 49000,
    golds: 310.0,
    fdi: 74,
  },
  'FR': {
    name: 'Pháp',
    code: 'FRA',
    flag: '🇫🇷',
    gdp: 2781,
    gdpGrowth: 0.7,
    inflation: 2.6,
    unemployment: 7.4,
    population: 68,
    gdpPerCapita: 41000,
    golds: 2436.0,
    fdi: 42,
  },
  'BR': {
    name: 'Brazil',
    code: 'BRA',
    flag: '🇧🇷',
    gdp: 1839,
    gdpGrowth: 2.9,
    inflation: 4.2,
    unemployment: 7.1,
    population: 215,
    gdpPerCapita: 8600,
    golds: 113.0,
    fdi: 65,
  },
  'IT': {
    name: 'Ý',
    code: 'ITA',
    flag: '🇮🇹',
    gdp: 2010,
    gdpGrowth: 0.7,
    inflation: 2.5,
    unemployment: 7.6,
    population: 56,
    gdpPerCapita: 35900,
    golds: 2451.8,
    fdi: 32,
  },
  'CA': {
    name: 'Canada',
    code: 'CAN',
    flag: '🇨🇦',
    gdp: 2116,
    gdpGrowth: 1.5,
    inflation: 2.7,
    unemployment: 5.5,
    population: 39,
    gdpPerCapita: 52000,
    golds: 178.5,
    fdi: 48,
  },
  'KR': {
    name: 'Hàn Quốc',
    code: 'KOR',
    flag: '🇰🇷',
    gdp: 1411,
    gdpGrowth: 1.4,
    inflation: 2.5,
    unemployment: 2.6,
    population: 51,
    gdpPerCapita: 27600,
    golds: 382.8,
    fdi: 29,
  },
  'SG': {
    name: 'Singapore',
    code: 'SGP',
    flag: '🇸🇬',
    gdp: 501,
    gdpGrowth: 1.1,
    inflation: 2.1,
    unemployment: 1.9,
    population: 5.9,
    gdpPerCapita: 85000,
    golds: 127.4,
    fdi: 141,
  },
  'HK': {
    name: 'Hồng Kông',
    code: 'HKG',
    flag: '🇭🇰',
    gdp: 397,
    gdpGrowth: 3.2,
    inflation: 1.6,
    unemployment: 2.9,
    population: 7.5,
    gdpPerCapita: 53000,
    golds: 291.5,
    fdi: 163,
  },
  'VN': {
    name: 'Việt Nam',
    code: 'VNM',
    flag: '🇻🇳',
    gdp: 430,
    gdpGrowth: 5.66,
    inflation: 3.15,
    unemployment: 2.24,
    population: 100.3,
    gdpPerCapita: 4280,
    golds: 113.0,
    fdi: 28,
  },
  'TH': {
    name: 'Thái Lan',
    code: 'THA',
    flag: '🇹🇭',
    gdp: 505,
    gdpGrowth: 2.6,
    inflation: 1.2,
    unemployment: 1.0,
    population: 72,
    gdpPerCapita: 7020,
    golds: 179.6,
    fdi: 16,
  },
  'ID': {
    name: 'Indonesia',
    code: 'IDN',
    flag: '🇮🇩',
    gdp: 1417,
    gdpGrowth: 5.1,
    inflation: 2.6,
    unemployment: 5.3,
    population: 277,
    gdpPerCapita: 5120,
    golds: 141.0,
    fdi: 29,
  },
  'PH': {
    name: 'Philippines',
    code: 'PHL',
    flag: '🇵🇭',
    gdp: 662,
    gdpGrowth: 6.3,
    inflation: 3.3,
    unemployment: 3.5,
    population: 120,
    gdpPerCapita: 5520,
    golds: 146.0,
    fdi: 9.5,
  },
  'MY': {
    name: 'Malaysia',
    code: 'MYS',
    flag: '🇲🇾',
    gdp: 531,
    gdpGrowth: 3.7,
    inflation: 1.8,
    unemployment: 3.5,
    population: 34,
    gdpPerCapita: 15600,
    golds: 40.7,
    fdi: 12,
  },
  'AU': {
    name: 'Úc',
    code: 'AUS',
    flag: '🇦🇺',
    gdp: 1723,
    gdpGrowth: 2.1,
    inflation: 3.6,
    unemployment: 3.7,
    population: 27,
    gdpPerCapita: 64000,
    golds: 312.6,
    fdi: 56,
  },
  'ZA': {
    name: 'Nam Phi',
    code: 'ZAF',
    flag: '🇿🇦',
    gdp: 405,
    gdpGrowth: 0.3,
    inflation: 6.5,
    unemployment: 28.7,
    population: 60,
    gdpPerCapita: 6750,
    golds: 125.3,
    fdi: 3.5,
  },
  'EG': {
    name: 'Ai Cập',
    code: 'EGY',
    flag: '🇪🇬',
    gdp: 476,
    gdpGrowth: 3.1,
    inflation: 31.1,
    unemployment: 6.8,
    population: 110,
    gdpPerCapita: 4330,
    golds: 84.0,
    fdi: 9.2,
  },
  'SA': {
    name: 'Ả Rập Xê Út',
    code: 'SAU',
    flag: '🇸🇦',
    gdp: 1061,
    gdpGrowth: 2.7,
    inflation: 2.0,
    unemployment: 4.6,
    population: 37,
    gdpPerCapita: 28700,
    golds: 322.9,
    fdi: 32,
  },
  'AE': {
    name: 'Tiểu Vương Quốc Ả Rập Thống Nhất',
    code: 'ARE',
    flag: '🇦🇪',
    gdp: 622,
    gdpGrowth: 3.9,
    inflation: 1.5,
    unemployment: 1.3,
    population: 9.9,
    gdpPerCapita: 62800,
    golds: 97.0,
    fdi: 198,
  },
  'IL': {
    name: 'Israel',
    code: 'ISR',
    flag: '🇮🇱',
    gdp: 543,
    gdpGrowth: 1.9,
    inflation: 3.3,
    unemployment: 3.9,
    population: 9.5,
    gdpPerCapita: 57100,
    golds: 196.3,
    fdi: 24,
  },
  'RU': {
    name: 'Nga',
    code: 'RUS',
    flag: '🇷🇺',
    gdp: 1858,
    gdpGrowth: 3.6,
    inflation: 5.9,
    unemployment: 2.8,
    population: 144,
    gdpPerCapita: 12900,
    golds: 3384.5,
    fdi: 5.8,
  },
};

// Generate additional data for other countries (simplified)
function generateCountryData(code, name, flag) {
  return {
    name: name,
    code: code,
    flag: flag,
    gdp: Math.random() * 5000,
    gdpGrowth: (Math.random() - 0.3) * 10,
    inflation: Math.random() * 8,
    unemployment: Math.random() * 12,
    population: Math.random() * 1500,
    gdpPerCapita: Math.random() * 80000,
    golds: Math.random() * 3000,
    fdi: Math.random() * 200,
  };
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = COUNTRIES_DATA;
}
