import type { FlowModel } from './types'

/**
 * Mock capital-flow data for Phase 5.
 * Values are approximate USD billions; timestamps are fixed for reproducibility.
 * No real API is consulted at this phase.
 */
export const MOCK_FLOWS: FlowModel[] = [
  // ── Trade flows ──────────────────────────────────────────────────────────
  {
    id: 'trade-us-cn',
    sourceCountry: 'US',
    targetCountry: 'CN',
    flowType: 'trade',
    value: 584,
    direction: 'bilateral',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'US–China bilateral trade', year: 2024 },
  },
  {
    id: 'trade-de-fr',
    sourceCountry: 'DE',
    targetCountry: 'FR',
    flowType: 'trade',
    value: 180,
    direction: 'bilateral',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'Germany–France bilateral trade', year: 2024 },
  },
  {
    id: 'trade-jp-us',
    sourceCountry: 'JP',
    targetCountry: 'US',
    flowType: 'trade',
    value: 220,
    direction: 'bilateral',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'Japan–US bilateral trade', year: 2024 },
  },
  {
    id: 'trade-cn-de',
    sourceCountry: 'CN',
    targetCountry: 'DE',
    flowType: 'trade',
    value: 260,
    direction: 'bilateral',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'China–Germany bilateral trade', year: 2024 },
  },
  {
    id: 'trade-gb-us',
    sourceCountry: 'GB',
    targetCountry: 'US',
    flowType: 'trade',
    value: 130,
    direction: 'bilateral',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'UK–US bilateral trade', year: 2024 },
  },
  {
    id: 'trade-in-us',
    sourceCountry: 'IN',
    targetCountry: 'US',
    flowType: 'trade',
    value: 128,
    direction: 'bilateral',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'India–US bilateral trade', year: 2024 },
  },
  {
    id: 'trade-br-cn',
    sourceCountry: 'BR',
    targetCountry: 'CN',
    flowType: 'trade',
    value: 145,
    direction: 'bilateral',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'Brazil–China bilateral trade', year: 2024 },
  },
  // ── Investment flows ──────────────────────────────────────────────────────
  {
    id: 'inv-us-gb',
    sourceCountry: 'US',
    targetCountry: 'GB',
    flowType: 'investment',
    value: 90,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'US FDI into UK', year: 2024 },
  },
  {
    id: 'inv-cn-au',
    sourceCountry: 'CN',
    targetCountry: 'AU',
    flowType: 'investment',
    value: 42,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'Chinese FDI into Australia', year: 2024 },
  },
  {
    id: 'inv-jp-vn',
    sourceCountry: 'JP',
    targetCountry: 'VN',
    flowType: 'investment',
    value: 35,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'Japan FDI into Vietnam', year: 2024 },
  },
  {
    id: 'inv-de-us',
    sourceCountry: 'DE',
    targetCountry: 'US',
    flowType: 'investment',
    value: 78,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'Germany FDI into US', year: 2024 },
  },
  {
    id: 'inv-us-in',
    sourceCountry: 'US',
    targetCountry: 'IN',
    flowType: 'investment',
    value: 55,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'US FDI into India', year: 2024 },
  },
  // ── Debt / bond flows ─────────────────────────────────────────────────────
  {
    id: 'debt-cn-ke',
    sourceCountry: 'CN',
    targetCountry: 'KE',
    flowType: 'debt',
    value: 12,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'Chinese sovereign loan to Kenya', year: 2024 },
  },
  {
    id: 'debt-jp-id',
    sourceCountry: 'JP',
    targetCountry: 'ID',
    flowType: 'debt',
    value: 18,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'Japan ODA loan to Indonesia', year: 2024 },
  },
  {
    id: 'debt-us-mx',
    sourceCountry: 'US',
    targetCountry: 'MX',
    flowType: 'debt',
    value: 22,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'US bond holdings in Mexico', year: 2024 },
  },
  // ── Aid flows ─────────────────────────────────────────────────────────────
  {
    id: 'aid-us-ua',
    sourceCountry: 'US',
    targetCountry: 'UA',
    flowType: 'aid',
    value: 75,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'US aid to Ukraine', year: 2024 },
  },
  {
    id: 'aid-de-ua',
    sourceCountry: 'DE',
    targetCountry: 'UA',
    flowType: 'aid',
    value: 22,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'Germany aid to Ukraine', year: 2024 },
  },
  {
    id: 'aid-gb-et',
    sourceCountry: 'GB',
    targetCountry: 'ET',
    flowType: 'aid',
    value: 4,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'UK development aid to Ethiopia', year: 2024 },
  },
  {
    id: 'aid-us-eg',
    sourceCountry: 'US',
    targetCountry: 'EG',
    flowType: 'aid',
    value: 1.5,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'US aid to Egypt', year: 2024 },
  },
  {
    id: 'aid-jp-ph',
    sourceCountry: 'JP',
    targetCountry: 'PH',
    flowType: 'aid',
    value: 5,
    direction: 'outbound',
    timestamp: '2024-01-01T00:00:00Z',
    metadata: { description: 'Japan ODA grant to Philippines', year: 2024 },
  },
]
